# Generated by Django 4.1.7 on 2023-03-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNum', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('description', models.TextField()),
                ('squareFeet', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
